---
title: "Lab Notebook"
author: "Madigan Boborci"
date: "2026-02-23"
date-modified: last-modified
format: 
  html:
    toc: true
    theme: cerulean
---

**This is Madigan's Lab Notebook. It was started in February 2026 to function as a log of work done, a to-do list, and a general place to workshop project ideas**

## Writing 
Need to update SOP! 
## Planning
Figure out dates to go Laniakea and other site



## Field Work 
### Daily Notes
**2/22/26** : Excursion to Turtle Bay! We got to the Ritz ~10:30, and were down on the sand ~10:45. The tide wasn't as low as I expected. Celia, Natalie and I began by identifying the GPS coordinate we had, and then took some [site photos](https://drive.google.com/drive/u/0/folders/1OQXG37OfbQFIea8StpXGFpf8WnhEXl1x). Tide was difficult to work with. We ended up setting out 8 vertical transects between 4 and 9 ish meters long to capture zonation across the site. GPS Points (Named T01 and T08 MB) were taken at the first and last transect points and rough GPS coordinates are captured with each photo as well. After those, we set up a 50 m transect roughly between those two points running parallel to the shore and took photoquads every 2 m. All photoquads can be found [here](https://drive.google.com/drive/u/0/folders/1yifGz-ZEIX5P8CrnjLmN2xJEVYOoqnHS). 
I was worried I didn't capture the best area, so I did some looking closer towards the point. I found similar algae comp and a few rock boring urchins, but no study species, and the rock was less consistent. I did find one Opihi at approx m 43 on our parallel transect!
We attempted to scout out Laniakea a little, but parking was practically impossible. I uploaded all photos to my shared [Madigan Boborci Drive](https://drive.google.com/drive/u/0/folders/0AEZZCGkxNF-uUk9PVA) in a [Field Work Photos Folder](https://drive.google.com/drive/u/0/folders/1-3IOwiSWHNMWt95N0L__JsfJaXnj5VEW) on 2/23/26. They are also being uplaoded to the lab desktops since we don't currently have hard drives. 



