---
title: "Lab Notebook"
author: "Madigan Boborci"
date: "2026-02-23"
date-modified: last-modified
format: 
  html:
    toc: true
    theme: cerulean
editor: 
  markdown: 
    wrap: 72
---

**This is Madigan's Lab Notebook. It was started in February 2026 to
function as a log of work done, a to-do list, and a general place to
workshop project ideas**

# Year 1

## Weekly summary/to do list/thoughts

**3/2-3/6** 

This week sucked personally. I did not get a lot done for
myself at all. However, we got the green light to go to Ka'upulehu for
the community meeting on 3/11 and I had a tile prototype 3D printed at
the PACE Makerspace. Minimal updates were made to SOP's and Protocols,
mostly just got the necessities done this week though.

**3/9-3/13** 

This week I printed off some handouts for the Big Island
meeting, and we went to Kona on Wed 3/11. Notes are below. Got a bunch
of ideas for side projects and edits for this project, all detailed in
planning or meetings. Reached out to Kanoe about one, setting up meeting
after spring break

**3/16-3/20** 

Spring break, graded one day that's about it

**3/23-3/27** 

Started this week thinking some more about the project,
did some additional reading, really need to just start writing some
stuff. Also need to start more photoquad analysis.

**3/30-4/3**

Went to a cafe with Natalie on 3/28 and actually started to draft my intro- need to add way more detail and flesh it out but better work than I've done in a few weeks. I also found a big dataset on Dryad called GlobTherm, which has lower and upper thermal limits for a bunch of species- I want to go through and find all the limu they have, checking with Jamie on Wednesday to see if that's a waste of time or not. Need to submit something for writing class this week- update this later to show whether I got my Intro to a solid point or if I write and submit my Patrick Conant Grant. No labs this week so hopefully a lot of writing time :). + a master's defense on zoom. *4/2 Update* Wrote a draft of my Introduction and worked with Jamie on it, interested to see what feedback I get. Also started fixing up my CV and outlining what I want to write for a scholarship (maybe 2). Went to Seanna's masters defense on nutrient impacted growth of native and invasive *Gracilaria* species on 4/1. Need to write my draft for the scholarship, finish updating my CV and do my grading. Also talked with Jamie and I probably am going to do an intertidal review paper as well as data wrangling for the GlobTherm Data set this summer. 

**4/6-4/10**

Went to GWISH Writing Kalapu on Sunday, wrote the first draft of the Patrick Conant Scholarship and was able to send it to Jamie on Monday. I also laid out drafts of my poster to try and see what works and what doesn't. Haven't done a lot of other writing, but will get feedback on my draft on Thursday and then can incorporate some of that. I also have to use the feedback Jamie gave on my scholarship. Classes also dropped this week. 

**4/13-4/17**

Volunteered with GWISH for the Radford High School Visit on Monday. Met with Kanoe and Jamie about side project at Haleamano and got a really positive response. Checking back in after the field school/ Fiona's grad. Zoomed with Jake, one of Donna's students for next year, about HI life etc. Went to workday with Natalie on Saturday, and had lunch which was fun. Sunday I ran errands and did work for the evening- big TA grading week

**4/20-4/24**

Found out I was accepted to HCC this week! Worked a lot on my poster and got feedback in lab meeting. Saturday I did a GWISH sanctioned tour of Waimea valley which was really cool, and then Natalie and I went diving on Sunday. Sent my poster for printing and graded a lot, and then had my meeting 

**4/27-5/1**

Registered for classes on Monday and then had a GWISH development event where we wrote long term goals and broke them up into chunks to make them manageable and more trackable. Reached out to a potential UR member this week, and hopefully she gets back to me. Went to Rob's Aquarium talk Wednesday night. Having lunch with Dr. Longman Thursday, and grading straggling assignments before the due date for final papers is next week. 
Chatted with Jamie about committee members and how to approach brainstorming chapter 3. 

**5/4-5/8**

Last week of the semester! Trying to sort out my driver's license, so a lot of random DMV trips. Having lunch with another prof candidate (Kristina Black) today, TESTERs is 5/6-8 with the poster session in the afternoon of the 6th, and I will have 16 scientific papers to grade by 5/7. Really need to lock in and write this one page Next Swell Grant but I'm really putting it off. TESTERs was great, I got some good reactions to my poster which was nice, and the banquet was very fun. Also had a GWISH end of year cruise Saturday so nothing got done this weekend.

**5/11-5/15**
Still need to grade still need to write next swell. Emailed Andy and Nyssa and asked them to be on my committee and they both said yes! Watched Hollie Putnam's seminar and then cut out of work early to go hang out with Quinn and Brooke. Had lunch with Hollie on Tues which was really nice. Built tile prototype Tues afternoon- it worked and we have more ideas about how to make it cleaner. Also testing the copper tape in water for a few days to see if it stays stuck to the tile (it did). Graded students' papers, had final grading meeting on Friday, and completed the BoatUS course and reached out to Max to schedule boating time. 

**5/18-5/22**
Been coming in to the lab to do tiles every day. Lots of trial and error, lots of tiles turned out great and some need a dremel to get down to proper size. Started an SOP for tile construction as well. Micah, Nyssa, Jamie and I met to go over intertidal things which was very much needed, and Micah helped me out with tiles as well. Helped Jamie reorganize the lab, picked up the drill press with Jamie and some other hardware and started helping to prep the Mark Hixon cage tiles for that experiment. Need to call Turtle Bay and chat with them about me being there,and need to figure out a wagon situation for my tiles. Called Turtle Bay and talked to a bunch of people, left Travis a message but haven't heard back. Jamie ordered wagon and toolbelts
Ran out of epoxy but will continue on the second half of the tiles next week. Made an SOP for tile construction - linked in protocol section below. 

**5/25-5/29**

Wrote [one pager](https://docs.google.com/document/d/1s4Xy8WLh9-062XD8cbZzWH0rlJ_sc_6_k2I5gCitPKw/edit?tab=t.0) to link to QR code. Went to GWISH writing hui on Tues and wrote Next Swell draft finally. got invited to go to Kanoe Field school field trips next week and going to site scout with Jamie 5/29. Emailed Prof Colwill back, submitted Next Swell Grant, numbered all tiles, configured HOBOs, need to finish Epoxy and actually print/affix the QR code I made.  

**6/1-6/15**

Wasn't good at keeping track after the semester ended. Epoxy never arrived so we decided to put out 30 tiles- 10 black, 10 white and 10 white with copper, with 4 hobos per treatment for black and white treatments. Met Uncle Wally and got to go on limu walks with Kanoe's field school, and Jaedon expressed interest in working with the lab. Affixed my QR code and logos to the 3D printed tile. Worked with Mica and weighed all the tiles in [this sheet](https://docs.google.com/spreadsheets/d/1NW849sbIr4eOkoG-cSkhJl8hQS1qwepnZ6trISD5f1E/edit?usp=drive_link) . Packed all materials necessary for tile deployment including permits in the wagon. Shawn, Jamie, and Mica deployed all 30 tiles at TB on Sunday, 6/14. Photos and updated GPS points [here](https://drive.google.com/drive/folders/1YoM3i7xDrrJE_mX5PDF6YSzWpyAwZGmS?usp=drive_link) . In airport I changed the photos on my poster to use deployment photos. Planning to go up to see them this week and do some quads (≥25) around the tiles. Also got invited to be put on the NCEAS CAGED Grant, so that could happen next year and am now the solo diver on the Mark Hixon project for August.

**6/16-6/19**

Tuesday came in to the office for a few hours and did some updating and lab cleanup. Wednesday, went with Natalie and Elle (SURF student) to see my tiles, do some photoquads around them and then we did four proficiency dives at Shark's Cove. Organized where extra intertidal hardware goes in lab, worked on Poster and Poster video talk, looking at tides to go scout other sites. 


**6/22-6/26**

6/23 I went to Waikiki MLCD with Natalie, Elle, and Wei Shen to try out some SFM and shore diving with the frames- it went bad. The waves were breaking and there were a lot of coral heads to navigate and then once we got out there the vis also sucked. I also crushed my phone in the van door, so I spent the afternoon at the Apple Store. Wed I recorded my virtual components for HCC and submitted them, and then I learned how to use Coral Net. I edited all my photoquads, and put them in coral net but then realized that it's better to use Image J to project a grid on top of the quads to analyze using visual estimation and a scale like from the Dethier and Sachowicz papers. Working on that today, 6/25. Going diving at Electric Beach tomorrow with Natalie and Elle to try and deploy again tomorrow. Also put in tentative dates for all my tile checks until the semester starts. Planning to site scout Ma'ili on Saturday am. Was going to go to Laniakea on Sunday, but they're closing the full highway so have to move that. Planning for Tile check 1 on June 30, still to be confirmed. Working on Protocols for Coral Net and FIJI

**7/6-7/10**
Tile Check 1 was good! One problem child tile so now we are going to bring tools in the field for each timepoint. The black tiles were 2 degrees hotter than the white tiles though! They had brown scuzz growing on them and the tiles with the lowest tidal height were definitely more gross than the ones higher up. Jamie and Shawn went and fixed all the problem children 7/2. Have been diving for Natalie. Got my O2 and other certs refreshed 7/3 so I can dive with DAR 7/7. Next tile timepoint will be 7/12. Writing FIJI protocol for photoquads as well. 



## Meetings

[One on One's with
Jamie](https://docs.google.com/document/d/12ytNMCWecb1Dq2ZZPArwK2R8OimJ_7zB5DGfRN-8ZUg/edit?tab=t.0)

## Reading Logs/Notes

-   [Celia Lit
    Review](https://docs.google.com/spreadsheets/d/1R4GAAFEjg1LdSK-zgPWDC2mXJ2kZTGOv8NrAQtC6U_0/edit?gid=0#gid=0)

-   [Rocky Intertidal Reading
    Notes](https://docs.google.com/spreadsheets/d/1msT-RtpQmMFPojSIdImeVUphKP-B--Rip673tEBEjiA/edit?gid=0#gid=0)

*more notes in Zotero as annotations as well*

## Writing

To Do:

-   Fix Intertidal 1 Intro
-   Patrick Conant Scholarship ✔️
-   Start Poster b/c Testers in like a month?  ✔️
-   Write Next Swell Grant and ask Jamie for LOR for that ✔️
-   Edit/ alter poster for HCC 
-   Prepare virtual components for HCC by June 20 ish


## Protocols

### Photoquadrat Analysis:

**2/27/26**

Organized Turtle Bay photos by transect, started a
[protocol](https://docs.google.com/document/d/1c0KI1wFTUMlBs6lImA5FDiBzJkXb2XVAH_c-jTt_gjo/edit?tab=t.0)
for analyzing, made a
[spreadsheet](https://docs.google.com/spreadsheets/d/1BXvRIjhm194BZ9sG7ba74MQEpcc-C0k6x_2KYsK4k4E/edit?gid=0#gid=0)
with metadata tab for data entry.

Questions:

-   Invertebrates- same spreadsheet? Count or stick with %?

-   Figure out how turf is named/defined and add in to metadata

-   Better column title than *Organism*?

**3/6** Didn't do a lot of work this week- but added a tab to the
photoquad analysis sheet for mobile orgs and count data to keep separate
and reduce NA's in my final data set by separating from algae %cover
etc. Also found definitions for turf, put in metadata and put citations
on protocol doc.

**3/10** Added some species ID photos to the metadata tab on the sheet

### SOP for Tile Building and deployment

**2/27/26**

Updated SOP for [tile construction and
deployment](https://docs.google.com/document/d/1DW0WNnjXcA0YuDPmdLnvpjQF-oLIWXvy39ayp5bGDKE/edit?tab=t.0)
with some things we had discussed (how to affix hobo, tagging methods,
etc)

**5/22/26**
New SOP for [Tile Construction](https://docs.google.com/document/d/1N9WLTkJpqm6fdt1tjkOh2z7lY6lPUy7Aybgto3CL8kI/edit?tab=t.0)


## Planning

***For site scouting/fieldwork, Micah suggested looking for low tide but
also wave energy \<100 kJ***

### Laniakea Site Scouting:

***All weather from forecasts on 2/26***

**March 7**

*Tide= 0.1ft from 9:28 to 10:09 am (low at 10:20 am)*

Would want to arrive about 9:00 (parking situation TBD), on sand by
9:15, work until 10:15-10:30 and be back by 12.

-   Swell/Waves:

    -   Surf Height: 2-3 ft

    -   Swell: 2 ft at 11 s from NW

    -   Wave Energy: 212 kJ at 10:00

-   Wind: 12 mph E; gusts of 28

-   Weather: Partly cloudy

**March 8**

*Tide= 0.2ft from 9:27 to 11:20 am (low at 10:44 am)*

Would want to arrive about 9:15 (parking situation TBD), on sand by
9:30, work until 10:30-10:45 and be back by 12:30.

-   Swell/Waves:

    -   Surf Height: 2-3 ft

    -   Swell: 1.4 ft at 11s from NW

    -   Wave Energy: 226 kJ at 10:00

-   Wind: 5 mph E; gusts of 14

-   Weather: Rain in the afternoon

### Project Planning 3/12 (Post Kalaemano Meeting)

Need to read papers and see if there's any information on life
history/settlement/ growth time for algae here. Is three months enough?
Or absolutely need more than that?

**New Summer Plan**

Instead of deploying at all sites, use Turtle Bay as a Pilot

-   n=60 max

-   do n=10 for each tile treatment (black and white)

    -   leave out June-Oct

    -   take temps with temp gun and photos every two weeks for 5 mos

    -   Don't soak, prove that we can get algae on the putty and without
        soaking so they're comparable to Kordas

-   Copper cross

    -   3 copper treatments x 2 heat treatments= 6

    -   maybe do 5 replicates?

    -   do we need to cross them with heat or do we just want to see if
        the tape works

        -   In that case maybe do 10 reps if we want and then just do
            the 3 copper treatments with white plates 

-   Settlement size comparison?

    -   on the n=20? or separate so we can see the results from the ones
        that follow Kordas with solid sample size

    -   If separate, use the last 10 tiles for this, and do n=5 for a 9
        and 11 cm settlement area? Or something similar. Can compare to
        the 10 that are Kordas sized

        -   Or just do n=10 for a 9 cm and compare to the n=10 for the 7
            cm

-If can't leave out for 6 mos, do n=10 at a lower tidal height to mimic soaking over the three months 

-   Cage some?

    -   This could also be done later

    -   I just want to see if it's possible to cage out fish

-   conduct field surveys for observational data (north shore sites
    only?) 

-   measure tidal heights and put a lag bolt at each site so we know
    where the different tidal heights are

### Madigan's side projects

-   Work with any limu data Kanoe already collects during her surveys

    -   See if there are differences in algae comp between open and
        closed take areas

    -   See if there are differences within closed and open areas
        (comapring a's and b's to their counterparts)

    -   Pair with ‘opihi density area to see how the harvest changes the
        limu communities

-   Totally different: putting cages on Mark's 3d printed things

    -   maybe Natalie does coral settlement and I can do algae comp or
        fish vids/follows

## Field Work

### Daily Notes

**2/22/26** :

*10:45 on the sand*

*0.0 tide at 11:34 am*

Excursion to Turtle Bay! We got to the Ritz \~10:30, and were down on
the sand \~10:45. The tide wasn't as low as I expected. Celia, Natalie
and I began by identifying the GPS coordinate we had, and then took some
[site
photos](https://drive.google.com/drive/u/0/folders/1OQXG37OfbQFIea8StpXGFpf8WnhEXl1x).
Tide was difficult to work with. We ended up setting out 8 vertical
transects between 4 and 9 ish meters long to capture zonation across the
site. GPS Points (Named T01 and T08 MB) were taken at the first and last
transect points and rough GPS coordinates are captured with each photo
as well. After those, we set up a 50 m transect roughly between those
two points running parallel to the shore and took photoquads every 2 m.
All photoquads can be found
[here](https://drive.google.com/drive/u/0/folders/1yifGz-ZEIX5P8CrnjLmN2xJEVYOoqnHS).
I was worried I didn't capture the best area, so I did some looking
closer towards the point. I found similar algae comp and a few rock
boring urchins, but no study species, and the rock was less consistent.
I did find one Opihi at approx m 43 on our parallel transect! We
attempted to scout out Laniakea a little, but parking was practically
impossible. I uploaded all photos to my shared [Madigan Boborci
Drive](https://drive.google.com/drive/u/0/folders/0AEZZCGkxNF-uUk9PVA)
in a [Field Work Photos
Folder](https://drive.google.com/drive/u/0/folders/1-3IOwiSWHNMWt95N0L__JsfJaXnj5VEW)
on 2/23/26. They are also being uploaded to the lab desktop and are on
Koa Cloud since we don't currently have hard drives.

## Ka‘ūpūlehu Community Meeting Notes/Overview

**3/11**

Flew out to Kona at 6:30 am with all the CoI's! Landed, went to a market
for snacks, Kanoe gave the lowdown on the community and some of the
other current affairs they're dealing with. We went to the Kalaemano
Interpretive Center, got there and then we did a circle on the grass
where we introduced ourselves briefly and shared kilo (intentional
observations) and then the Mo'olelo portion of the metting was a
fisheries activity led by Madison. Then we presented first:

-   Frame project with Mo'olelo about the intertidal going forward

-   Add in some sort of signage?

    -   A QR Code

    -   Kari said she would put it on their social media

    -   Madison said they could also put it in the resort, and
        incorporate more signage there and bring it into their outreach

    -   should have project overview, contact info, Jamie Website,
        Kalaemano website

-   Biofilms?

-   Soak Tiles..?

    -   Terracotta/ceramic instead of putty settlement area?

        -   Easier to soak, could make removable settlement area for
            Nyssa

    -   Jamie doesn't want to- doesn't compare to Kordas

        -   see Planning section for what to do instead

-   Timeline

    -   Funding

    -   Permits- all received now

    -   Nyssa equipment

    -   Tile Soaking?

    -   Try Wait opening potentially July 1

        -   Where is best to put the tiles? In closed or open area?

        -   Block them? (Please no I can't do the stats for that)

        -   Put them in areas where the security cams work and work with
            security to add some help protecting them

After presenting, we listened to the Ch91 fishing plan updates, and then
had a delicious lunch. Afterwards, we changed and did a shoreline walk,
got to see the area and the issues we may have. The tide was a 0.2 at
2:30, but the wave energy was pretty close to unworkable at only 120 kJ.
We chatted a lot about logistics/other project and side project ideas,
including how we would need an AirBnb practically on the water to do
ecosystem function processing there. Concerns include the settlement
area size, material, whether to soaks, timeline of tile deploy,
questioning whether they can be surveyed every two weeks, and if they
need to be left out for longer than three months.

After the shoreline walk, we hung out a bit, said goodbye, and headed to
the airport. An amazing day overall and good connections were built and
solid questions were raised.

See Planning section for thoughts on addressing concerns above.



**6/17**

Went out to see the tiles!

30 tiles installed 6/14 by Jamie, Shawn and Mica. Deployed 10 white, 10 black with 8 HOBOS and 10 white tiles with copper taped base plates. Notes from deployment found [here](https://docs.google.com/document/d/1L9CThIV817rrDNA_QEY4z_4ybCSI4d3Jg4JIrzIgj0M/edit?tab=t.9y2q2pgu6sva)

6/17 went out with Natalie and her SURF student Elle. Low tide was at 8:54 (-0.3), arrived at 8:40 ish. Took [photoquads](https://drive.google.com/drive/folders/1cMDGRiF89F_k8hCe2T4CAP-Hf--MKVbc) - One after block 10, 2 between other blocks, and 1 before block 1 for n=20. Light brown scuzz already forming on tiles. Lots of dessicated algae. 



**6/27**

Went to scout out Ma'ili. Some available bench area, only about 40 m of great space, one side has a lot of ridge-y areas and the other is a stream outlet. Different Algae community, but still patches of limu kala so I see us putting thew tiles at that tidal height to match TB. I got there at 7:00 am, tide was at -0.1 according to surfline, which is what it said the low was which was at 7:38. Wave energy was 138 kJ, which did make the transect hard with one person, but not impossible. Did a 40 m parallel to shore and 5 transects perpendicular to shore along that same area. Lots of photos, on Google and Koa and will be on Lab desktop. Man came up to me as I was leaving and asked me what I was doing, and his response seemed good!

**6/30** 

Went with Mica to my first tile Timepoint. Arrived at about 7:15, just before low tide (-0.3). All tiles were exposed. One tile (11A) had one full anchor and bolt out of the substrate. Otherwise, tiles were cleaned, photos and photoquads taken, and HOBOs checked. Black tiles were ~2 degress hotter than white! Jamie and Shawn fixed 11A, and another problem tile, and tightened all lags on all tiles. In the future, we will bring tools at each time point to do this. 

## Committee Formation

Potential: Jamie (obviously)

Nyssa ✔️

Andy ✔️

Mark Hixon, Erik Franklin, Eileen Nalley, or Liz Madin?

UR:
[Requirements](https://docs.google.com/document/d/10IhSs-RT1QU3pZNTT_-8epBK6Fu6FLYo7520ppnLoag/edit?tab=t.0)

[Women and Gender Studies
Dept](https://manoa.hawaii.edu/graduate/select-committee-member/#)

  - Emailed Dr. Colwill- haven't heard back as of 5/5. Will email Stephanie Teves and Ayu Saraswati in a few weeks if I don't get ahold of Elizabeth. 
  Elizabeth said yeas for committee!


### Brainstorming Chpt 3

*Herbivory as fish move from intertidal to coral reefs*

Ontogeny feels a bit big for one chapter, but maybe just the linking of nutrient dist, drying and taking nutrients from each int and reef and seeing difference in contents, idk how else to do this but figure out fish movement and level of herbivory between the two locations


How algae diversity supports fish nursery habitats?
Cage the urchins fish and birds out 
